Allow container to resolve command dependencies via handle()
imdhemy/laravel-in-app-purchases pull request #238
Opened 2022-12-31 12:13 UTC by cosmastech

| Q             | A                                                                        |
|---------------|--------------------------------------------------------------------------|
| Branch?       | `release/1.x`|
| Bug fix?      | yes                                                                  |
| New feature?  | no |
| Deprecations? | no  |
| Tickets       | Fix #237 |
| License       | MIT                                                                      |

Removes `__construct()` calls (as they are fully inherited), adds typehints to `handle()` methods instead.

2022-12-31 13:56 UTC, imdhemy commented
Thanks, @cosmastech, could you please fix the broken tests?

2023-01-01 11:58 UTC, cosmastech commented
> Thanks, @cosmastech, could you please fix the broken tests?

It looks like this is a feature of Laravel 9 😢 .

I can close this if you do not have plans of upgrading the base Laravel version.

2023-01-01 12:06 UTC, imdhemy commented
The good news is I'm already working on the next major version [2.x], just rebase your changes from the `master` branch so we can publish your changes.

2023-01-01 13:09 UTC, cosmastech commented
Test are still failing. Will look into this today, may not be a L9 feature, but I have no clue why this change would cause them to fail.

2023-01-01 15:36 UTC, imdhemy commented
I think this is related to the injected services in tests. The doubles should be injected when running tests. If you managed to conditionally inject them into the handle method the tests will pass. 

https://github.com/imdhemy/laravel-in-app-purchases/blob/616fe877c0dea2f2783ee2bb65c3ce39624282d8/tests/Doubles/LiapTestProvider.php#L30-L48

2023-01-01 15:57 UTC, cosmastech commented
> I think this is related to the injected services in tests. The doubles should be injected when running tests. If you managed to conditionally inject them into the handle method the tests will pass.
> 
> https://github.com/imdhemy/laravel-in-app-purchases/blob/616fe877c0dea2f2783ee2bb65c3ce39624282d8/tests/Doubles/LiapTestProvider.php#L30-L48

Got it.

Would you be opposed to removing the conditional provider? We can create Concerns that bind the Doubles to the container and instantiate them from the TestCase::setUp() for the 3 tests like so:

```php
trait BindsAppStoreTestDouble {
    protected function bindAppStoreTestDouble(): void {
        $this->app->bind(AppStoreTestNotificationServiceBuilder::class, AppStoreTestNotificationServiceBuilderDouble::class);
    }
}
```

and then within the test classes:
```php
protected function setUp(): void
{
    parent::setUp();

    $this->privateKey = $this->generateP8Key();

    $this->bindAppStoreTestDouble()
}
```

2023-01-01 16:39 UTC, imdhemy commented
I prefer to bind them in a service provider, which is already done in the shared snippet. Even the code contains a conditional binding, but just binding is enough because that service provider is only registered on tests.

The problem is, looks like the conditional binding works for the constructor but doesn't work for the `handle()` method.

---

The following would make the console tests pass:

```php
$this->app->bind(
            UrlGeneratorContract::class,
            UrlGeneratorDouble::class
        );
        
        $this->app->bind(
            AppStoreTestNotificationServiceBuilder::class,
            AppStoreTestNotificationServiceBuilderDouble::class
        );
```

---

And there will be only one remaining [broken test](https://github.com/imdhemy/laravel-in-app-purchases/blob/616fe877c0dea2f2783ee2bb65c3ce39624282d8/tests/Handlers/AbstractNotificationHandlerTest.php#L11), which can be fixed by replacing the Url generator namespace:

```diff
- use Imdhemy\Purchases\Contracts\UrlGenerator;
+ use Imdhemy\Purchases\Console\UrlGenerator;
```

2023-01-01 17:53 UTC, cosmastech commented
Given that this can work with L8 (I believe), would you prefer that I base onto 1.x? Or just leave it for `master`?

2023-01-02 08:33 UTC, imdhemy commented
basing onto 1.x looks good.

2023-01-02 08:38 UTC, imdhemy requested changes

2023-01-02 08:38 UTC, imdhemy commented on tests/Doubles/LiapTestProvider.php
> +        if ($this->app->runningUnitTests()) {
This check is not needed. The `LiapTestProvider` is only registered in tests.

2023-01-02 08:38 UTC, imdhemy commented on tests/Doubles/LiapTestProvider.php
> +        $appStoreTestNotificationServiceBuilderClass = AppStoreTestNotificationServiceBuilder::class;
Let's use the class names directly without creating variables.

2023-01-02 14:21 UTC, imdhemy approved these changes

2023-01-02 14:21 UTC, merged

2023-01-02 14:21 UTC, imdhemy commented
Thanks @cosmastech 🙌

2023-01-02 14:22 UTC, cosmastech commented
> Thanks @cosmastech 🙌

Thanks for building this great package and letting me contribute @imdhemy